### PR TITLE
Allowing JtsGeometry to handle homogenous collections.

### PR DESCRIPTION
**Pull request by jdeolive**
Added method to attempt to “narrow” the collection if possible by
checking through its contents.

### CODE REVIEW

**Comment by sttawm** [comment]
Have you taken a look at `GeometryFactory.buildGeometry()`? It sounds like it and `narrowCollectionIfPossible` have the same (or very similar) functionality.

**Comment by jdeolive** [comment]
Ahh, indeed, that method does have what I need. I'll update this pull request accordingly.

**Comment by jdeolive** [comment]
Ok, update made, thanks for the tip!

Also, let me know if you think this should be optional behaviour and require a configuration parameter to engage. Happy to do so.

**Comment by dsmiley** [comment]
Thanks Justin (and for your input @sttawm )

**Pull request merged**
